apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
images:
  - name: 040531138489.dkr.ecr.ap-northeast-2.amazonaws.com/week6-argocd/sample-app
    newTag: v1
