apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: >-
      app=040531138489.dkr.ecr.ap-northeast-2.amazonaws.com/week6-argocd/sample-app
    argocd-image-updater.argoproj.io/app.update-strategy: latest
    argocd-image-updater.argoproj.io/app.pull-secret: ext:/scripts/ecr-login.sh
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: workloads
  source:
    repoURL: https://github.com/pyy0715/gitops-lab.git
    targetRevision: main
    path: manifests/04_image-updater/dev-app
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
