apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.tenant }}
  labels:
    app: {{ .Values.tenant }}
    tier: {{ .Values.tier }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.tenant }}
  template:
    metadata:
      labels:
        app: {{ .Values.tenant }}
        tier: {{ .Values.tier }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
