apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tenant }}
  labels:
    app: {{ .Values.tenant }}
    tier: {{ .Values.tier }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.tenant }}
  ports:
    - port: 80
      targetPort: 80
